name = "ur_pilot"
description = "Configuration file for the chargepal ur_pilot package."
author = "Georg John"
email = "georg.john@dfki.de"

[robot]
home_radians = [3.429, -1.371, 2.127, -0.747, 1.867, -1.565]
ip_address = "192.168.13.42"

[robot.joints]
vel = 0.35
max_vel = 0.5
acc = 0.1
max_acc = 0.5

[robot.tcp]
vel = 0.1
max_vel = 0.2
acc = 0.1
max_acc = 0.2

[robot.tool]
mass = 0.4
com = [0.00057, 0.00017, 0.0089]
tip_frame = [0.0, 0.0, 0.195, 0.0, 0.0, 0.0]
sense_frame = [-0.025, 0.0, 0.19417, 0.0, -0.2618, 0.0]

[robot.servo]
vel = 0.0
acc = 0.0
gain = 100.0
lkh_time = 0.2

[robot.force_mode]
mode = 2
gain = 0.99
damping = 0.075
tcp_speed_limits = [0.025, 0.025, 0.025, 0.025, 0.025, 0.025]

[robot.motion_mode]
error_scale = 10000.0
Kp = [10.0, 10.0, 10.0, 10.0, 10.0, 10.0]
Kd = [0.01, 0.01, 0.01, 1e-5, 1e-5, 1e-5]

[robot.hybrid_mode]
error_scale = 150.0
force_limit = 20.0
Kp_force = [0.02, 0.02, 0.02, 0.02, 0.02, 0.02]
Kd_force = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
Kp_motion = [150.0, 150.0, 150.0, 150.0, 150.0, 150.0]
Kd_motion = [0.99, 0.99, 0.99, 0.99, 0.99, 0.99]
