name = "ur_pilot"
description = "Configuration file for the chargepal ur_pilot package."
author = "Georg John"
email = "georg.john@dfki.de"

[robot]
home_radians = [3.429, -1.371, 2.127, -0.747, 1.867, -1.565]
ip_address = "192.168.13.42"

[robot.joints]
vel = 0.1
max_vel = 0.5
acc = 0.1
max_acc = 0.5

[robot.tcp]
vel = 0.1
max_vel = 0.2
acc = 0.1
max_acc = 0.2

[robot.tool]
mass = 1.65471266
com = [0.00012, -0.00010, 0.06190]
# mass = 1.67637663
# com = [0.00005, 0.00010, 0.06102]

[robot.ft_sensor]
adapter = "enx3c18a01939b0"  # "enp3s0"  #
filter_sinc_length = 128  # (51, 64, 128, 205, 256, 512)
filter_fir = false
filter_fast = false
filter_chop = false
ft_bias = [12.62421, -2.70075, -24.21888, -0.08053, -0.09157, 0.02465]
# ft_bias = [11.44241, -1.75967, -24.60086, -0.05484, -0.05863, 0.01714]

[robot.servo]
vel = 0.0
acc = 0.0
gain = 100.0
lkh_time = 0.2

[robot.force_mode]
mode = 2
gain = 0.99
damping = 0.075
tcp_speed_limits = [0.01, 0.01, 0.01, 0.01, 0.01, 0.01]

name = "ur_pilot"
description = "Configuration file for the chargepal ur_pilot package."
author = "Georg John"
email = "georg.john@dfki.de"

# mass = 1.68551096
# com = [0.00003, -0.00020, 0.06070]
# ft_bias = [11.50438, -1.67830, -24.49330, -0.05331, -0.05752, 0.02054]
