name = "ur_control"
description = "Configuration file for the ur_control package."
author = "Georg John"
email = "georg.john@dfki.de"

[robot]
tool = "None"
home_radians = [3.429, -1.371, 2.127, -0.747, 1.867, -1.565]
ip_address = "192.168.13.42"

[robot.joints]
vel = 0.35
max_vel = 0.5
acc = 0.1
max_acc = 0.5

[robot.tcp]
vel = 0.1
max_vel = 0.2
acc = 0.1
max_acc = 0.2
